### ISSUE TITLE
python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by irickman** [jldbc/pybaseball#33]
It seems like it's giving me an error on the requests dependency, but I have requests 2.18.4 and have tried updating to 2.19.1 

Here's the full error message:

Collecting pybaseball
  Using cached https://files.pythonhosted.org/packages/73/ed/032d64eddfbc0acad1cc509e5376ae63161f5ba2e079039ef04794fb51b7/pybaseball-1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s6/5hjjzxbs17g8t1ch00w6whvm0000gn/T/pip-install-pvC6TX/pybaseball/setup.py", line 90, in <module>
        'requests>=2.18.1'],
      File "/Users/irarickman/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/irarickman/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/Users/irarickman/anaconda2/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Users/irarickman/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/Users/irarickman/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/Users/irarickman/anaconda2/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 592, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (certifi 2018.01.18 (/Users/irarickman/anaconda2/lib/python2.7/site-packages), Requirement.parse('certifi==2016.9.26'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s6/5hjjzxbs17g8t1ch00w6whvm0000gn/T/pip-install-pvC6TX/pybaseball/

**Comment by jldbc** [comment]
Hm, I don't think anything with this package has changed with respect to requests. What command are you running? Does `sudo pip install --upgrade pybaseball` give the same error?

I'm also seeing [this issue](https://github.com/facebook/prophet/issues/418) where a similar error was resolved by updating setuptools. Can you try that as well?

**Comment by irickman** [comment]
Yep, same error using pip install --upgrade. I similarly saw the posts about setuptools and have the most up to date version, but I'm still getting the same error

**Comment by jldbc** [comment]
Installing from scratch worked for me in a virtualenv. What happens when you `pip uninstall pybaseball` and then re-install?
